version: '3.1'

services:
  backend:
    restart: unless-stopped
    build: ./backend
    command: python /app/server.py -l 0.0.0.0 -p 1280 -r redis://redis -f
    depends_on:
      - redis
    ports:
      - '127.0.0.1:1280:1280'

  frontend:
    restart: unless-stopped
    build: ./frontend
    volumes:
      - /var/onliapa/frontend-build:/build
    ports:
      - '127.0.0.1:1281:1281'

  redis:
    restart: unless-stopped
    image: redis
    volumes:
      - /var/onliapa/redis-data:/data
