version: '3.1'

services:
  backend:
    build: ./backend
    command: python /app/server.py -l 0.0.0.0 -p 1280 -r redis://redis
    ports:
      - '1280:1280'

  frontend:
    build: ./frontend
    volumes:
      - /var/onliapa/frontend-build:/build

  redis:
    image: redis
    volumes:
      - /var/onliapa/redis-data:/data
